server {
    listen 80;
    location / {
        root    /usr/share/nginx/html;
        index   index.html;
        try_files $uri $uri/ /index.html;

        # 브라우저 캐시 방지 설정 (중요)
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}